# Normally this file would be excluded from the Git repository as it would contain sensitive information
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  secretData: U3VwI3JTM2NyZXReJQ==
